"""ajout du champ nin sur visitor

Le NIN sénégalais n'est pas encodé dans le MRZ (vérifié sur une CNI réelle, voir
ADR-005) : `numero_document` porte le numéro de carte extrait du MRZ, et ce nouveau
champ nullable accueille le NIN saisi manuellement par l'agent de contrôle.

Revision ID: 5f1c5bd2957b
Revises: e7bf70c4d387
Create Date: 2026-08-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1c5bd2957b'
down_revision: Union[str, Sequence[str], None] = 'e7bf70c4d387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('nin', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_visitors_nin'), 'visitors', ['nin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitors_nin'), table_name='visitors')
    op.drop_column('visitors', 'nin')
    # ### end Alembic commands ###
