"""initial schema

Schéma initial complet : utilisateurs, référentiels (services/agents/motifs),
visiteurs, visites et liste de révocation des refresh tokens.

Revision ID: e7bf70c4d387
Revises:
Create Date: 2026-08-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7bf70c4d387'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purposes',
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purposes')),
    sa.UniqueConstraint('libelle', name=op.f('uq_purposes_libelle'))
    )
    op.create_table('services',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['services.id'], name=op.f('fk_services_parent_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('identifiant', sa.String(length=100), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('poste', sa.String(length=150), nullable=True),
    sa.Column('role', sa.Enum('AGENT_CONTROLE', 'SUPERVISEUR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_identifiant'), ['identifiant'], unique=True)

    op.create_table('visitors',
    sa.Column('prenom', sa.String(length=150), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('type_document', sa.Enum('CNI', 'PASSEPORT', 'PERMIS', name='document_type'), nullable=False),
    sa.Column('numero_document', sa.String(length=60), nullable=False),
    sa.Column('nationalite', sa.String(length=60), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.Enum('M', 'F', name='sexe'), nullable=True),
    sa.Column('date_expiration_document', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('provenance', sa.String(length=200), nullable=True),
    sa.Column('immatriculation_vehicule', sa.String(length=40), nullable=True),
    sa.Column('mrz_image_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitors'))
    )
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitors_nom'), ['nom'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_numero_document'), ['numero_document'], unique=False)

    op.create_table('agents',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('office', sa.String(length=100), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_agents_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_service_id'), ['service_id'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revoked_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens'))
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('visits',
    sa.Column('visitor_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('purpose_id', sa.Uuid(), nullable=True),
    sa.Column('motif_libre', sa.String(length=500), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.Enum('PRESENT', 'SORTI', name='visit_status'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.Uuid(), nullable=False),
    sa.Column('checked_out_by', sa.Uuid(), nullable=True),
    sa.Column('client_reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_visits_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], name=op.f('fk_visits_checked_in_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['checked_out_by'], ['users.id'], name=op.f('fk_visits_checked_out_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], name=op.f('fk_visits_purpose_id_purposes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_visits_service_id_services'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_visits_visitor_id_visitors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_checked_in_at'), ['checked_in_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_client_reference'), ['client_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_visits_service_id'), ['service_id'], unique=False)
        batch_op.create_index('ix_visits_statut_checked_in_at', ['statut', 'checked_in_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_visitor_id'))
        batch_op.drop_index('ix_visits_statut_checked_in_at')
        batch_op.drop_index(batch_op.f('ix_visits_service_id'))
        batch_op.drop_index(batch_op.f('ix_visits_client_reference'))
        batch_op.drop_index(batch_op.f('ix_visits_checked_in_at'))
        batch_op.drop_index(batch_op.f('ix_visits_agent_id'))

    op.drop_table('visits')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_service_id'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))

    op.drop_table('agents')
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_numero_document'))
        batch_op.drop_index(batch_op.f('ix_visitors_nom'))

    op.drop_table('visitors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_identifiant'))

    op.drop_table('users')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_code'))

    op.drop_table('services')
    op.drop_table('purposes')
    # ### end Alembic commands ###

    # `drop_table` ne supprime pas les types ENUM natifs de PostgreSQL : sans ça,
    # un downgrade suivi d'un upgrade échouerait sur « type already exists ».
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for enum_name in ('visit_status', 'sexe', 'document_type', 'user_role'):
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
